### ISSUE TITLE
Smarter MapRenderer update strategy to only render new layers

### ISSUE THREAD

**Issue by imathews** [SEL-Columbia/cwp-epu-data-platform#11]
Currently, we're clearing the map and re-rendering everything on an update event (e.g., when the filters are toggled).

We should only redraw those layers that are affected. This might require a bit of a change to the filter piping; we need to keep track of the currently applied filters within the MapRenderer

**Comment by sfmcintyre** [comment]
- Improved with #22 
- final piece would be to potentially update vector rendering, starting at MapRenderer.js line 110 (`layer.clearLayers();`)
    - ideally, if a filter is updated, only features within that layer would be redrawn. but may not be feasible without extensive `vectorLayer.hasLayer(featureLayer)` checks (performance?), feel free to chat with me about new strategy
