### ISSUE TITLE
Style vectors to match map colors

### ISSUE THREAD

**Issue by sfmcintyre** [SEL-Columbia/cwp-epu-data-platform#21]
- [NOTE] the following plan depends on the current 'one color per vector set' paradigm. if we change this (e.g., different colored vectors within a set, according to a metadata value, as specified in #15), let's reconsider this plan
- use the `<Select />` component's `styles` property to configure styles according to each vectors `leafletOptions.style` parameter
- `styles` property can be configured according to the [`react-select` spec](https://react-select.com/styles), and modeled off of the [Custom Styles example](https://react-select.com/home#custom-styles)
- useful resource: [`chroma-js`](https://gka.github.io/chroma.js/) allows comparing and shifting colors to handle hovered/selected/active/etc states

**Comment by imathews** [comment]
@sfmcintyre is this still relevant?

**Comment by sfmcintyre** [comment]
prefer use of colors for single metadata value as in #15
