### ISSUE TITLE
Improve base layers, consider mapbox-gl

### ISSUE THREAD

**Issue by imathews** [SEL-Columbia/cwp-epu-data-platform#24]
Right now, the terrain and street base layers aren't great. I've been trying to find better raster tilesets on Mabpox, but there really isn't much available.

It seems like there's a big push to use vector tilesets (https://docs.mapbox.com/help/how-mapbox-works/mapbox-data/), which would allow us to style the different layers and give us access to better basemaps (e.g., https://www.mapbox.com/gallery/#cali-terrain)

Leaflet doesn't support vector tiles out of the box, but there are plugins (https://openmaptiles.org/docs/website/leaflet/). However, I'm wondering if we should migrate to mabpox-gl (https://docs.mapbox.com/mapbox-gl-js/api/) — the interface is pretty similar to Leaflet, and I think it supports all the same functionality of drawing features on top of the basemap, while providing much smoother zoom behavior and better mapbox integration.

It might be worth playing around a bit with mapbox Studio (https://studio.mapbox.com/) to see what kind of basemaps we can create and if this is a path worth exploring.

**Comment by sfmcintyre** [comment]
will wait until we have finished + released (green dot?) styles on studio.mapbox.com before closing
